[project]

[api]
release_date = "2025-06-01"
host = "localhost"
port = 8000
debug = true
reload = true

[database]
name = "sjenk"
url = "sqlite:///sjenk.db"
echo = true

[logging]
path = "./logs"
time_fmt = "YYYY-MM-DD_HH:mm:ss!UTC"
log_id_len = 8
level_len = 8
line_len = 4
name_len = 30
function_len = 30
message_len = 0
deduct_len = 13

[logging.console]
level = "TRACE"
show_categories = true

[logging.file]
levels = ["DEBUG", "ERROR"]
serialize=false
rotation="1 days"
retention="30 days"
compression="zip"