[api]
host = "localhost"
port = 8000

[db]
name = "sjenk"
url = "sqlite:///./sjenk.sqlite3"

[logging]
path = "./logs"

[logging.stdout]
level = "TRACE"
backtrace = true
diagnose = true
colorize = true

[logging.stderr]
level = "ERROR"
backtrace = true
diagnose = true
colorize = true

[logging.file]
levels = ["TRACE", "ERROR"]
backtrace = true
diagnose = true
enqueue=true
colorize=true
serialize=false
rotation="1 days"
retention="30 days"
compression="zip"

[logging.slack]
level = "ERROR"
webhook = ""

[logging.email]
level = "CRITICAL"
subject = "Sjenk Critical Error"
to = "some@email.com"
from_ = "someother@email.com"
host = "smtp.gmail.com"
port = 25
login = false