[project]

[api]
release_date = "2025-06-01"
host = "localhost"
port = 8000
debug = true
reload = true

[database]
name = "sjenk"
url = "sqlite:///sjenk.db"
echo = true

[logging]
path = "./logs"
intercept = false
temp_filter = "~|||~"
time_fmt = "YYYY-MM-DD_HH:mm:ss!UTC"
log_id_len = 8
level_len = 8
line_len = 4
name_len = 30
function_len = 30
message_len = 0
deduct_len = 13
specific_loggers = ["sqlalchemy.engine.Engine", "uvicorn"]

[logging.console]
level = "DEBUG"
show_categories = true

[logging.file]
levels = ["DEBUG", "ERROR"]
serialize=false
rotation="1 days"
retention="30 days"
compression="zip"

[openapi]
url = "/openapi.json"
tags = '''
[
    {
        "name": "users",
        "description": "Operations with users.",
        "externalDocs": {
            "description": "External docs",
            "url": "https://lewiuberg.github.io/sjenk/api/endpoints/users/"
        }
    },
    {
        "name": "places",
        "description": "Operations with places.",
        "externalDocs": {
            "description": "External docs",
            "url": "https://lewiuberg.github.io/sjenk/api/endpoints/places/"
        }
    },
    {
        "name": "bookings",
        "description": "Operations with bookings.",
        "externalDocs": {
            "description": "External docs",
            "url": "https://lewiuberg.github.io/sjenk/api/endpoints/bookings/"
        }
    }
]
'''