name: Generate CITATION.cff

on:
  push:
    branches:
      - dev

jobs:
  generate-citation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Add ./src/api to PATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:./src/api" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyconfs toml pyyaml

      - name: Generate CITATION.cff
        run: |
          python src/api/utils/generate_citation.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add CITATION.cff
          git commit -m 'Generate CITATION.cff'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
